//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandardFramework.Tools.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StandardFramework.Tools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The assembly to use. Required..
        /// </summary>
        internal static string AssemblyDescription {
            get {
                return ResourceManager.GetString("AssemblyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration to use..
        /// </summary>
        internal static string ConfigurationDescription {
            get {
                return ResourceManager.GetString("ConfigurationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The namespace to use. Matches the directory by default..
        /// </summary>
        internal static string ExceptionsNamespaceDescription {
            get {
                return ResourceManager.GetString("ExceptionsNamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory to put files in. Paths are relative to the project directory. Defaults to &quot;Models.&lt;MODEL&gt;.Exceptions&quot;..
        /// </summary>
        internal static string ExceptionsOutputDirDescription {
            get {
                return ResourceManager.GetString("ExceptionsOutputDirDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target framework..
        /// </summary>
        internal static string FrameworkDescription {
            get {
                return ResourceManager.GetString("FrameworkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate model exception files.
        /// </summary>
        internal static string GenerateExceptionsDescription {
            get {
                return ResourceManager.GetString("GenerateExceptionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show JSON output..
        /// </summary>
        internal static string JsonDescription {
            get {
                return ResourceManager.GetString("JsonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required argument &apos;{0}&apos;..
        /// </summary>
        internal static string MissingArgument {
            get {
                return ResourceManager.GetString("MissingArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required option &apos;--{0}&apos;..
        /// </summary>
        internal static string MissingOption {
            get {
                return ResourceManager.GetString("MissingOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the model.
        /// </summary>
        internal static string ModelNameDescription {
            get {
                return ResourceManager.GetString("ModelNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The models directory..
        /// </summary>
        internal static string ModelsDirDescription {
            get {
                return ResourceManager.GetString("ModelsDirDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to the startup project file..
        /// </summary>
        internal static string ProjectDescription {
            get {
                return ResourceManager.GetString("ProjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project directory. Defaults to the current working directory..
        /// </summary>
        internal static string ProjectDirDescription {
            get {
                return ResourceManager.GetString("ProjectDirDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining arguments: {0}..
        /// </summary>
        internal static string RemainingArguments {
            get {
                return ResourceManager.GetString("RemainingArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The root namespace. Defaults to the target assembly name..
        /// </summary>
        internal static string RootNamespaceDescription {
            get {
                return ResourceManager.GetString("RootNamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The startup assembly to use. Defaults to the target assembly..
        /// </summary>
        internal static string StartupAssemblyDescription {
            get {
                return ResourceManager.GetString("StartupAssemblyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to the project file..
        /// </summary>
        internal static string StartupProjectDescription {
            get {
                return ResourceManager.GetString("StartupProjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using application base &apos;{0}&apos;..
        /// </summary>
        internal static string UsingApplicationBase {
            get {
                return ResourceManager.GetString("UsingApplicationBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using assembly &apos;{0}&apos;..
        /// </summary>
        internal static string UsingAssembly {
            get {
                return ResourceManager.GetString("UsingAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using models directory &apos;{0}&apos;..
        /// </summary>
        internal static string UsingModelsDir {
            get {
                return ResourceManager.GetString("UsingModelsDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using project directory &apos;{0}&apos;..
        /// </summary>
        internal static string UsingProjectDir {
            get {
                return ResourceManager.GetString("UsingProjectDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using root namespace &apos;{0}&apos;..
        /// </summary>
        internal static string UsingRootNamespace {
            get {
                return ResourceManager.GetString("UsingRootNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using startup assembly &apos;{0}&apos;..
        /// </summary>
        internal static string UsingStartupAssembly {
            get {
                return ResourceManager.GetString("UsingStartupAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using working directory &apos;{0}&apos;..
        /// </summary>
        internal static string UsingWorkingDirectory {
            get {
                return ResourceManager.GetString("UsingWorkingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The working directory of the tool invoking this command..
        /// </summary>
        internal static string WorkingDirDescription {
            get {
                return ResourceManager.GetString("WorkingDirDescription", resourceCulture);
            }
        }
    }
}
